### PR TITLE
(maint) Flush cli messages; send errors to stderr

### PR DESCRIPTION
**Pull request by rbrw**
Flush cli-error and cli-help messages in main before System/exit, since
the JVM doesn't necessarily flush on exit, and redirect cli-error messages
to stderr, to follow the normal command-line convention.

### CODE REVIEW

**Comment by cprice404** [comment]
+1

**Comment by KevinCorcoran** [comment]
:+1: Looks good to me.

@rbrw Out of curiosity, did you actually observe any cases of messages not getting flushed before shutdown?

**Comment by rbrw** [comment]
@KevinCorcoran yes, and you can probably demonstrate it by altering a "lein new app foo" core.clj to include a (System/exit 1) right after the hello world.

**Comment by rbrw** [comment]
@KevinCorcoran at least that demonstrates it here.

**Comment by jeffmccune** [comment]
:+1:

**Pull request merged**
